language: node_js
node_js:
- 6
install:
- npm install -g pm2
- npm install
script:
- pm2 deploy production
before_install:
- openssl aes-256-cbc -K $encrypted_cfad76373366_key -iv $encrypted_cfad76373366_iv -in .travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
addons:
  ssh_known_hosts: uedsky.com:1224
